### Creating a Vector

In [1]:
import numpy as np

#create a vector as a row
vector = np.array([1,2,3])

#create a vector as a column
vector = np.array([[1],
                  [2],
                  [3]])

### Creating a matrix

In [4]:
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

In [5]:
# Numpy actually has a dedicated matrix data structre:
matrix_object = np.mat([[1,2], 
                        [1,2], 
                        [1,3]])

### Creating a sparse matrix

In [11]:
from scipy import sparse

matrix = np.array([[0,0],
                  [0,1],
                  [3,1]])

# Create compressed sparse roe (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

Sparse matrices only store nonzero elements and assume all other values will be zero,
leading to significant computational savings. In our solution, we created a NumPy
array with two nonzero values, then converted it into a sparse matrix. If we view the
sparse matrix we can see that only the nonzero values are stored.

In [13]:
print(matrix_sparse) #display index and element

  (1, 1)	1
  (2, 0)	3
  (2, 1)	1


### Select elements

In [15]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])

In [16]:
vector[2]

3

In [17]:
matrix[1,1]

5

### Describing a matrix

In [22]:
matrix.shape

(3, 3)

In [23]:
matrix.size

9

In [24]:
matrix.ndim

2

### Applying Operations to elements

In [26]:
#Create function that adds 100 to something
add_100 = lambda i: i+100

#Create vectorized function
vectorized_add = np.vectorize(add_100)
vectorized_add(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

NumPy’s vectorize class converts a function into a function that can apply to all ele‐
ments in an array or slice of an array. It’s worth noting that vectorize is essentially a
for loop over the elements and does not increase performance. Furthermore, NumPy
arrays allow us to perform operations between arrays even if their dimensions are not
the same (a process called broadcasting). For example, we can create a much simpler
version of our solution using broadcasting

In [28]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### find Max and Min

In [30]:
np.max(matrix)

9

In [31]:
np.min(matrix)

1

In [32]:
# Find element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [33]:
#Find element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

### Calculating avg, variance and standard deviation

In [35]:
print(f'{np.mean(matrix)} Mean')
print(f'{np.var(matrix)} Variance')
print(f'{np.std(matrix)} Standard Deviation')

5.0 Mean
6.666666666666667 Variance
2.581988897471611 Standard Deviation


### Reshaping Arrays

In [41]:
matrix = np.array([[1,2,3], [1,2,3], [2,3,1], [7,8,9]])
matrix.reshape(2,6)

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 1, 7, 8, 9]])

### Transposing a Vector or Matrix

In [43]:
matrix

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 1],
       [7, 8, 9]])

In [44]:
matrix.T

array([[1, 1, 2, 7],
       [2, 2, 3, 8],
       [3, 3, 1, 9]])

### Flattening matrix

In [46]:
matrix.flatten()

array([1, 2, 3, 1, 2, 3, 2, 3, 1, 7, 8, 9])

### Finding the rank of a matrix
The rank of a matrix is the dimensions of the vector space spanned by its columns or
rows.

In [49]:
np.linalg.matrix_rank(matrix)

3

### Calculating determinant 

In [52]:
matrix = np.array([[1,2], [1,1]])

np.linalg.det(matrix)

-1.0

### Geting diagonal of a matrix

In [54]:
matrix.diagonal()

array([1, 1])

### Calculating trace of a matrix
The trace of a matrix is the sum of the diagonal elements and is often used under the
hood in machine learning methods.

In [56]:
matrix.trace()

2

### FInding Eigenvalues and Eigenvectors

In [58]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)


In [59]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [60]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### Dot products

In [62]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a, vector_b)

32

### Inverting matrix
The inverse of a square matrix, A, is a second matrix A–1, such that:
AA^(−1)= I

In [64]:
np.linalg.inv(matrix)

array([[ 1.18181818e+00, -1.00000000e+00,  2.72727273e-01],
       [-2.72727273e-01,  1.51394049e-17,  9.09090909e-02],
       [-1.51515152e-01,  3.33333333e-01, -6.06060606e-02]])

### Generate evenly spaced 4 numbers between 10 to 20

In [3]:
np.linspace(10, 20, 5) #5 evenly spaced numbers between 10 to 20

<IPython.core.display.Javascript object>

array([10. , 12.5, 15. , 17.5, 20. ])

### Create array of random numbers

In [5]:
#Create and array of random va;ues
np.random.random(4)

<IPython.core.display.Javascript object>

array([0.7366756 , 0.01280232, 0.96022084, 0.72861669])

In [6]:
# Generate an array of random integer numbers
np.random.randint(0, 300, 4)

<IPython.core.display.Javascript object>

array([ 66, 222, 111, 132])

In [8]:
# Using random.seed we can generate same number of random number
np.random.seed(123)
np.random.randint(0, 100, 10)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [2]:
# Generate array of Random of float numbers
f1 = np.random.uniform(5, 10, size=(10))
f1

array([7.12999562, 5.58206009, 6.25135309, 9.50642742, 9.03034232,
       6.23835342, 5.94543153, 8.13249547, 5.95512144, 7.03474865])

### Extract integer part


In [5]:
np.floor(f1)

array([7., 5., 6., 9., 9., 6., 5., 8., 5., 7.])

### Truncate decimal part

In [7]:
np.trunc(f1)

array([7., 5., 6., 9., 9., 6., 5., 8., 5., 7.])