# Vectors, Matrices, and Arrays

### 1.1. Creating a Vector

#### Problem
You need to create a vector. 

#### Solution
Use numpy to create a one-dimensional array.

In [6]:
import numpy as np
vector_row = np.array([1,2,3])
vector_column = np.array([[1],[2],[3]])

### 1.2. Creating a Matrix

#### Problem
You need to create a matrix. 

#### Solution
Use numpy to create a two-dimensional array.

In [8]:
matrix = np.array([[1,2],
                  [2,3],
                  [3,4]])

In [12]:
matrix_object = np.mat([[1,2], 
                        [2,3], 
                        [3,4]])


However, the matrix data structure is not recommended because the vast majority of NumPy operations return arrays, not matrix objects.


### 1.3. Creating a Sparse Matrix

#### Problem
Given data with very few nonzero values, you want to efficiently represent it. 
 
#### Solution
Create a Sparse matrix.

In [15]:
import numpy as np
from scipy import sparse

matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])
matrix_sparse = sparse.csr_matrix(matrix)

Sparse matrices only store nonzero elements and assume all other values will be zero, leading to significant computational savings. In our solution, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored:


In [17]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the nonzero values 1 and 3, respectively.
We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [22]:
matrix_large = np.array([[0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0],
                        [3,0,0,0,0,0,0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large) 

In [36]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [37]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

### 1.4. Selecting Elements

#### Problem
You need to select one or more elements in a vector or matrix.

#### Solution
Numpy array make that easy.

In [42]:
#row vector
vector = np.array([1,2,3,4,7,8])

#matrix
matrix = np.array([[1,2,3],
                  [2,3,4],
                  [4,7,8]])

In [45]:
vector[2]

3

In [46]:
vector[:2]

array([1, 2])

In [44]:
matrix[2]

array([4, 7, 8])

In [47]:
matrix[:2,:2]

array([[1, 2],
       [2, 3]])

### 1.5. Describing a Matrix 

#### Problem
You want to describe the shape, size and dimension of the matrix.

#### Solution
Use shape, size,and ndim

In [54]:
matrix = np.array([[1,2,3,4],
         [1,2,3,4],
         [4,3,2,1]])

#View number of rows and columns
print(matrix.shape)

#View number of elements (rows*columns)
print(matrix.size)

#View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


### 1.6. Applying Operations to Elements

#### Problem
You want to apply some function to multiple elements in an array. 
 
#### Solution
Use numpy's vectorsize

In [56]:
# Create matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#create function that adds 100 to something.
add_100 = lambda i:i+100

#create vectorized function
vec_add_100 = np.vectorize(add_100)

#Apply function to all elements in matrix
vec_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting

In [58]:
#Add 100 to all elements
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### 1.7. Finding min and max values

#### Problem
You need to find the max and min value in an array. 
 
#### Solution
Use numpy's max and min.

In [60]:
matrix = np.array([[1, 2, 3],                   
                   [4, 5, 6],                   
                   [7, 8, 9]])
print(np.min(matrix))
print(np.max(matrix))

1
9


In [61]:
#Find maximum element in each column
np.max(matrix, axis = 0)

array([7, 8, 9])

In [62]:
#Find minimum element in each row
np.min(matrix, axis = 1)

array([1, 4, 7])

### 1.8.  Calculating the Average, Variance, and Standard Deviation 

#### Problem
You want to calculate some descriptive statistics about an array.
 
#### Solution
Use numpy's mean, var, std.

In [64]:
matrix = np.array([[1, 2, 3],                   
                   [4, 5, 6],                   
                   [7, 8, 9]])
print(f'Mean: {np.mean(matrix)}')
print(f'Variance: {np.var(matrix)}')
print(f'Standard Deviation: {np.std(matrix)}')
                  

Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


### 1.9. Reshaping Arrays 

#### Problem
You want to change the shape of an array without changing elements.
 
#### Solution
Use numpy's reshape.

In [66]:
matrix = np.array([[1, 2, 3],                   
                   [4, 5, 6],                   
                   [7, 8, 9],                   
                   [10, 11, 12]])
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:


In [68]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:


In [73]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 Transposing a Vector or Matrix

#### Problem
You need to transpose a vector or matrix

#### Solution
Use the T method

In [75]:
matrix = np.array([[1, 2, 3],                   
                   [4, 5, 6],                   
                   [7, 8, 9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

A vector cannot be transposed because it is just a collection of values. 
However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:


In [77]:
np.array([[1,2,3,7,8,9]]).T

array([[1],
       [2],
       [3],
       [7],
       [8],
       [9]])

### 1.11. Flattening a matrix

#### Problem
You need to transform a matrix into a 1D array

#### Solution 
Use flatten


In [79]:
matrix = np.array([[1, 2, 3],                   
                   [4, 5, 6],                   
                   [7, 8, 9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# we can use reshape to create a row vector:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 1.12. Calculating the Determinant

#### Problem
You need to know the determinant of a matrix.

#### Solution 
Use Numpy's linear algebra method det

In [83]:
matrix = np.array([[1,2,3],[1,2,3],[2,3,4]])
np.linalg.det(matrix)

0.0

### 1.13. Getting the Diagonal of a Matrix

#### Problem
You need to get the diagonal elements of a matrix.

#### Solution
Use diagonal

In [85]:
matrix.diagonal()

array([1, 2, 4])

### 1.14. Calculating the Trace of a matrix

#### Problem
You need to calculate the trace of a matrix

#### Solution
Use trace

In [87]:
matrix.trace()

7

The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. We can also return the diagonal of a matrix and calculate its sum:

In [89]:
sum(matrix.diagonal())

7

### 1.15. Finding Eigenvalues and Eigenvectors

#### Problem
You need to find the eigenvalues and eigenvectors of a square matrix

#### Solution
Use numpy's linalg.eig

In [91]:
matrix = np.array([[1, -1, 3],                   
                   [1, 1, 6],                   
                   [3, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)


In [92]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [93]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### 1.16 Calculating Dot Products

#### Problem
You need to calculate the dot product of two vectors

#### Solution
Use Numpy's dot

In [96]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

np.dot(vec1, vec2)

32

### 1.17. Adding and Subtracting Matrices

#### Problem
You want to add or subtract two matrices.

#### Solution
Use numpy's add and Subtract

In [98]:
# Create matrix 
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# Create matrix 
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [99]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

### 1.18. Inverting Matrix

#### Problem
You want to calculate the inverse of a square matrix

#### Solution
Use Numpy's linear algebra inv method.

In [101]:
mat = np.array([[1,4],
               [2,5]])
np.linalg.inv(mat)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

### 1.19. Generating Random Values

#### Problem
You want to generate pseudorandom values.

#### Solution
Use Numpy's random

In [104]:
np.random.seed(0) #set seed
np.random.random(3) #random floats between 0 and 1.0

array([0.5488135 , 0.71518937, 0.60276338])

In [109]:
# Generate three random integers between 1 and 10 
print(np.random.randint(0, 11, 3))

#Alternatively, we can generate numbers by drawing them from a 
#distribution:

# Draw three numbers from a normal distribution with mean 0.0 # and standard deviation of 1.0 
print(np.random.normal(0.0, 1.0, 3))

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0 
print(np.random.logistic(0.0, 1.0, 3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0 
print(np.random.uniform(1.0, 2.0, 3))


[9 9 0]
[-2.55298982  0.6536186   0.8644362 ]
[-0.17585043  0.27546455 -3.95547251]
[1.6176355  1.61209572 1.616934  ]
