1. Import numpy as np and see the version

In [2]:
import numpy as np
print(np.__version__)

1.15.4


How to create a 1D array?

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

How to create a boolean array?

In [11]:
#method 1
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# Method 2
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [16]:
arr = np.arange(10)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [19]:
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Replace all odd numbers in arr with -1 without changing arr

In [21]:
arr =np.arange(10)
out=np.where(arr%2!=0, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Convert a 1D array to a 2D array with 2 rows

In [24]:
arr = np.arange(10)
arr.reshape(2, -1) # setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Stack arrays a and b vertically

In [27]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

In [28]:
# Method 1

np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# Method 2

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# Method 3 
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack arrays a and b horizontally

In [32]:
# Method 1

np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [34]:
# Method 2

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [35]:
# Method 3 
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

 Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
 
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
a = np.array([1,2,3])

In [42]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Get a commom items between a and b

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
np.intersect1d(a,b)

array([2, 4])

From array a remove all items present in array b

In [47]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

Get the positions where elements of a and b match

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [50]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

Get all items between 5 and 10 from a

In [53]:
a = np.array([2,6,1,9,10,3,27])

In [54]:
# Method 1

index = np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

In [55]:
# Method 2

index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [56]:
# Method 3

a[(a>5) & (a<=10)]

array([ 6,  9, 10])

Swap two columns in a 2d numpy array

In [62]:
arr = np.arange(9).reshape(3, -1)
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [63]:
17

17